### PR TITLE
Bump Scala to 2.12.20

### PR DESCRIPTION
**Pull request by Fokko**
Adds support for JDK21+:

- https://github.com/scala/scala/releases/tag/v2.12.18
- https://github.com/scala/scala/releases/tag/v2.12.19
- https://github.com/scala/scala/releases/tag/v2.12.20

Or see: https://endoflife.date/scala#jdk-compatibility

### CODE REVIEW

**Comment by Fokko** [comment]
@pan3793 I don't have full visibility on that, but it doesn't like it, looking at `Usages` in Maven Central: https://mvnrepository.com/artifact/org.apache.parquet/parquet-scala

**Comment by pan3793** [comment]
+1 for retiring the `parquet-scala` module, or even dropping it directly.

there is only one class in the `parquet-scala` module, users are easy to copy and embed it if we drop the `parquet-scala` module.

additionally, it's rare to publish a scala lib that only supports a single scala binary version, most scala libs support 2~3 scala binary versions in each version

**Comment by Fokko** [comment]
@pan3793 I agree, are you interested in raising a `[DISCUSS]` on the mailinglist?

**Comment by pan3793** [comment]
@Fokko https://lists.apache.org/thread/scdq9t2gvvs4glhq0qx4qcvfp62j793s

**Comment by Fokko** [comment]
Closing this in favor of https://github.com/apache/parquet-java/pull/3063

**Pull request closed without merging**
