### PR TITLE
MINOR: Bump version to 1.16.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

The snapshot version should be bumped after releasing 1.15.0.

### What changes are included in this PR?

Bump version to 1.16.0-SNAPSHOT and update japicmp previous version.

### Are these changes tested?

Pass CIs.

### Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by wgtmac** [comment]
Is it time to bump the version to 2.0-SNAPSHOT? @Fokko @gszadovszky

**Comment by Fokko** [comment]
Ah, I wanted to do this as well, thanks for picking this up @wgtmac. Regarding `2.0-SNAPSHOT`, that might be a good question to discuss at the sync later today.

**Review by Fokko — APPROVED** [review]

**Comment by Fokko** [comment]
The docs suggest running the major release in October: https://parquet.apache.org/docs/contribution-guidelines/releasing/#release-cadence

**Comment by wgtmac** [comment]
We can bump it to 1.16.0-SNAPSHOT for now. A major version bump is something serious to discuss.

**Pull request merged**
